<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\box-bottom\BoxBottom.Auth.Business\BoxBottom.Auth.Business.csproj" />
    <ProjectReference Include="..\..\box-bottom\BoxBottom.Auth.Contract\BoxBottom.Auth.Contract.csproj" />
    <ProjectReference Include="..\..\box-bottom\BoxBottom.Auth.Controllers\BoxBottom.Auth.Controllers.csproj" />
    <ProjectReference Include="..\..\box-bottom\BoxBottom.Auth.Entra\BoxBottom.Auth.Entra.csproj" />
    <ProjectReference Include="..\..\box-bottom\BoxBottom.Auth.ZeroAuth\BoxBottom.Auth.ZeroAuth.csproj" />
    <ProjectReference Include="..\..\box-bottom\BoxBottom.Users.Contract\BoxBottom.Users.Contract.csproj" />
    <ProjectReference Include="..\..\box-bottom\BoxBottom.Users.Data\BoxBottom.Users.Data.csproj" />
    <ProjectReference Include="..\BoxPack.Users.Customization\BoxPack.Users.Customization.csproj" />
  </ItemGroup>


</Project>
