<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BoxBottom.Auth.Business\BoxBottom.Auth.Business.csproj" />
    <ProjectReference Include="..\BoxBottom.Auth.Contract\BoxBottom.Auth.Contract.csproj" />
    <ProjectReference Include="..\BoxBottom.Users.Contract\BoxBottom.Users.Contract.csproj" />
    <ProjectReference Include="..\BoxBottom.Users.Controllers\BoxBottom.Users.Controllers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BoxBottom.Auth.Entra\BoxBottom.Auth.Entra.csproj" />
    <ProjectReference Include="..\BoxBottom.Auth.ZeroAuth\BoxBottom.Auth.ZeroAuth.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.10" />
  </ItemGroup>

</Project>
