<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" Version="13.4.3" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" Version="13.4.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BoxBottom.Aspire.Orchestration\BoxBottom.Aspire.Orchestration.csproj" />
    <ProjectReference Include="..\BoxBottom.AzureTable.Emulation\BoxBottom.AzureTable.Emulation.csproj" />
  </ItemGroup>

</Project>
