<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BoxBottom.Auth.Contract\BoxBottom.Auth.Contract.csproj" />
    <ProjectReference Include="..\BoxBottom.Azure.Table\BoxBottom.Azure.Table.csproj" />
    <ProjectReference Include="..\BoxBottom.Users.Contract\BoxBottom.Users.Contract.csproj" />
  </ItemGroup>

</Project>
