<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\box-bottom\BoxBottom.Aspire.ServiceDefaults\BoxBottom.Aspire.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\box-bottom\BoxBottom.Auth.Emulation\BoxBottom.Auth.Emulation.csproj" />
    <ProjectReference Include="..\..\box-bottom\BoxBottom.Emulation\BoxBottom.Emulation.csproj" />
    <ProjectReference Include="..\..\box-pack\BoxPack.Auth.Customization\BoxPack.Auth.Customization.csproj" />
    <ProjectReference Include="..\..\box-pack\BoxPack.Users.Customization\BoxPack.Users.Customization.csproj" />
    <ProjectReference Include="..\..\box-bottom\BoxBottom.AzureTable.Emulation\BoxBottom.AzureTable.Emulation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.5.1" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BoxTest.Aspire.Orchestration.Test" />
  </ItemGroup>

</Project>
